---
name: dispatch_coverity

on: workflow_dispatch

jobs:
  dispatch_coverity:
    name: Dispatch static analysis with coverity
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        run: echo "Dispatching Coverity run"